# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6813a738a2aba65f30fa848898e0cb90e3c739c9191a645d1612da0e81632087cd3a7ecd7a49e43cee219f1fb8ea433d34a707a142e6500b007461901249eaa8

test:
  secret_key_base: 3d39e61d620f7464fd60e2f11bac5c5d8fa114bf49cbdb1e4024a7099a9727db4a42a3170c92d224e5c2c21f5e491f09df3f09aad97b869be91a7a72aad7a2d6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
